-- MySQL Script generated by MySQL Workbench
-- Thu Sep 18 16:28:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(100) NOT NULL,
  `emailCliente` VARCHAR(100) NOT NULL UNIQUE,
  `telefoneCliente` VARCHAR(20) NOT NULL,
  `senhaCliente` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Unidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Unidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Unidade` (
  `idUnidade` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `nomeUnidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUnidade`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Barbeiro`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `mydb`.`Barbeiro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Barbeiro` (
  `idBarbeiro` INT NOT NULL AUTO_INCREMENT,
  `nomeBarbeiro` VARCHAR(100) NOT NULL,
  `emailBarbeiro` VARCHAR(100) NOT NULL UNIQUE,
  `telefoneBarbeiro` VARCHAR(20) NOT NULL,
  `senhaBarbeiro` VARCHAR(255) NOT NULL,
  `statusBarbeiro` ENUM('Ativo', 'Inativo') NOT NULL,
  `dataRetorno` DATE DEFAULT NULL,
  `Unidade_idUnidade` INT NOT NULL,
  PRIMARY KEY (`idBarbeiro`),
  CONSTRAINT `fk_Barbeiro_Unidade`
    FOREIGN KEY (`Unidade_idUnidade`)
    REFERENCES `mydb`.`Unidade` (`idUnidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `mydb`.`Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `nomeServico` VARCHAR(100) NOT NULL,
  `descricaoServico` VARCHAR(255) NOT NULL,
  `duracaoPadrao` INT NOT NULL,
  `precoServico` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `mydb`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `nomeAdmin` VARCHAR(100) NOT NULL,
  `emailAdmin` VARCHAR(100) NOT NULL UNIQUE,
  `telefoneAdmin` VARCHAR(20) NOT NULL,
  `senhaAdmin` VARCHAR(255) NOT NULL,
  `Unidade_idUnidade` INT NULL,
  PRIMARY KEY (`idAdministrador`),
  CONSTRAINT `fk_Administrador_Unidade`
    FOREIGN KEY (`Unidade_idUnidade`)
    REFERENCES `mydb`.`Unidade` (`idUnidade`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `mydb`.`Agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Agendamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Agendamento` (
  `idAgendamento` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `statusAgendamento` ENUM('Agendado', 'Cancelado', 'Finalizado') NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Barbeiro_idBarbeiro` INT NOT NULL,
  `Unidade_idUnidade` INT NOT NULL,
  PRIMARY KEY (`idAgendamento`),
  CONSTRAINT `fk_Agendamento_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_Agendamento_Barbeiro`
    FOREIGN KEY (`Barbeiro_idBarbeiro`)
    REFERENCES `mydb`.`Barbeiro` (`idBarbeiro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `uk_Barbeiro_Horario`
    UNIQUE (`Barbeiro_idBarbeiro`, `data`, `hora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agendamento_has_Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Agendamento_has_Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Agendamento_has_Servico` (
  `Agendamento_idAgendamento` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  `precoFinal` DECIMAL(10,2) NOT NULL,
  `tempoEstimado` INT NOT NULL,
  PRIMARY KEY (`Agendamento_idAgendamento`, `Servico_idServico`),
  CONSTRAINT `fk_AgServ_Agendamento`
    FOREIGN KEY (`Agendamento_idAgendamento`)
    REFERENCES `mydb`.`Agendamento` (`idAgendamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AgServ_Servico`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Unidade_has_Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Unidade_has_Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Unidade_has_Servico` (
  `Unidade_idUnidade` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  PRIMARY KEY (`Unidade_idUnidade`, `Servico_idServico`),
  CONSTRAINT `fk_Unidade_has_Servico_Unidade`
    FOREIGN KEY (`Unidade_idUnidade`)
    REFERENCES `mydb`.`Unidade` (`idUnidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Unidade_has_Servico_Servico`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Barbeiro_has_Servico`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `mydb`.`Barbeiro_has_Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Barbeiro_has_Servico` (
  `Barbeiro_idBarbeiro` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  PRIMARY KEY (`Barbeiro_idBarbeiro`, `Servico_idServico`),
  CONSTRAINT `fk_Barbeiro_has_Servico_Barbeiro`
    FOREIGN KEY (`Barbeiro_idBarbeiro`)
    REFERENCES `mydb`.`Barbeiro` (`idBarbeiro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Barbeiro_has_Servico_Servico`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
