-- MySQL Script generated by MySQL Workbench
-- Thu Sep 18 16:28:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(100) NOT NULL,
  `emailCliente` VARCHAR(100) NOT NULL UNIQUE,
  `telefoneCliente` VARCHAR(20) NOT NULL,
  `senhaCliente` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Unidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Unidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Unidade` (
  `idUnidade` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `nomeUnidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUnidade`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Barbeiro`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `mydb`.`Barbeiro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Barbeiro` (
  `idBarbeiro` INT NOT NULL AUTO_INCREMENT,
  `nomeBarbeiro` VARCHAR(100) NOT NULL,
  `emailBarbeiro` VARCHAR(100) NOT NULL UNIQUE,
  `telefoneBarbeiro` VARCHAR(20) NOT NULL,
  `senhaBarbeiro` VARCHAR(255) NOT NULL,
  `statusBarbeiro` ENUM('Ativo', 'Inativo') NOT NULL,
  `dataRetorno` DATE DEFAULT NULL,
  `Unidade_idUnidade` INT NOT NULL,
  PRIMARY KEY (`idBarbeiro`),
  CONSTRAINT `fk_Barbeiro_Unidade`
    FOREIGN KEY (`Unidade_idUnidade`)
    REFERENCES `mydb`.`Unidade` (`idUnidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `mydb`.`Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `nomeServico` VARCHAR(100) NOT NULL,
  `descricaoServico` VARCHAR(255) NOT NULL,
  `duracaoPadrao` INT NOT NULL,
  `precoServico` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `mydb`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `nomeAdmin` VARCHAR(100) NOT NULL,
  `emailAdmin` VARCHAR(100) NOT NULL UNIQUE,
  `telefoneAdmin` VARCHAR(20) NOT NULL,
  `senhaAdmin` VARCHAR(255) NOT NULL,
  `Unidade_idUnidade` INT NULL,
  PRIMARY KEY (`idAdministrador`),
  CONSTRAINT `fk_Administrador_Unidade`
    FOREIGN KEY (`Unidade_idUnidade`)
    REFERENCES `mydb`.`Unidade` (`idUnidade`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `mydb`.`Agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Agendamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Agendamento` (
  `idAgendamento` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `statusAgendamento` ENUM('Agendado', 'Cancelado', 'Finalizado') NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Barbeiro_idBarbeiro` INT NOT NULL,
  `Unidade_idUnidade` INT NOT NULL,
  PRIMARY KEY (`idAgendamento`),
  CONSTRAINT `fk_Agendamento_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_Agendamento_Barbeiro`
    FOREIGN KEY (`Barbeiro_idBarbeiro`)
    REFERENCES `mydb`.`Barbeiro` (`idBarbeiro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `uk_Barbeiro_Horario`
    UNIQUE (`Barbeiro_idBarbeiro`, `data`, `hora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agendamento_has_Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Agendamento_has_Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Agendamento_has_Servico` (
  `Agendamento_idAgendamento` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  `precoFinal` DECIMAL(10,2) NOT NULL,
  `tempoEstimado` INT NOT NULL,
  PRIMARY KEY (`Agendamento_idAgendamento`, `Servico_idServico`),
  CONSTRAINT `fk_AgServ_Agendamento`
    FOREIGN KEY (`Agendamento_idAgendamento`)
    REFERENCES `mydb`.`Agendamento` (`idAgendamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_AgServ_Servico`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Unidade_has_Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Unidade_has_Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Unidade_has_Servico` (
  `Unidade_idUnidade` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  PRIMARY KEY (`Unidade_idUnidade`, `Servico_idServico`),
  CONSTRAINT `fk_Unidade_has_Servico_Unidade`
    FOREIGN KEY (`Unidade_idUnidade`)
    REFERENCES `mydb`.`Unidade` (`idUnidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Unidade_has_Servico_Servico`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Barbeiro_has_Servico`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `mydb`.`Barbeiro_has_Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Barbeiro_has_Servico` (
  `Barbeiro_idBarbeiro` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  PRIMARY KEY (`Barbeiro_idBarbeiro`, `Servico_idServico`),
  CONSTRAINT `fk_Barbeiro_has_Servico_Barbeiro`
    FOREIGN KEY (`Barbeiro_idBarbeiro`)
    REFERENCES `mydb`.`Barbeiro` (`idBarbeiro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Barbeiro_has_Servico_Servico`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ======= ADIÇÕES BESPOKE 2025-10: METAS/COMISSÕES, FLAGS DE SENHA, ÍNDICES =======

-- Alterar Barbeiro: obrigar troca de senha após reset e validade da temporária
ALTER TABLE `mydb`.`Barbeiro`
  ADD COLUMN `deveTrocarSenha` TINYINT(1) NOT NULL DEFAULT 0 AFTER `dataRetorno`,
  ADD COLUMN `senhaTempExpiraEm` DATE NULL AFTER `deveTrocarSenha`;

-- Índices para acelerar relatórios
CREATE INDEX `idx_agendamento_unidade_data` ON `mydb`.`Agendamento` (`Unidade_idUnidade`, `data`);
CREATE INDEX `idx_agendamento_barbeiro_data` ON `mydb`.`Agendamento` (`Barbeiro_idBarbeiro`, `data`);
CREATE INDEX `idx_agendamento_status` ON `mydb`.`Agendamento` (`statusAgendamento`);

-- Tabela de metas por unidade
DROP TABLE IF EXISTS `mydb`.`Meta`;
CREATE TABLE `mydb`.`Meta` (
  `idMeta` INT NOT NULL AUTO_INCREMENT,
  `Unidade_idUnidade` INT NOT NULL,
  `periodicidade` ENUM('Semanal','Mensal') NOT NULL,
  `inicio` DATE NOT NULL,
  `fim` DATE NOT NULL,
  `base` ENUM('Receita','Atendimentos') NOT NULL,
  `objetivoValor` DECIMAL(10,2) NOT NULL,
  `percentualFlat` DECIMAL(5,2) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idMeta`),
  CONSTRAINT `fk_Meta_Unidade` FOREIGN KEY (`Unidade_idUnidade`) REFERENCES `mydb`.`Unidade` (`idUnidade`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Overrides de objetivo por barbeiro (opcional)
DROP TABLE IF EXISTS `mydb`.`MetaBarbeiro`;
CREATE TABLE `mydb`.`MetaBarbeiro` (
  `idMetaBarbeiro` INT NOT NULL AUTO_INCREMENT,
  `Meta_idMeta` INT NOT NULL,
  `Barbeiro_idBarbeiro` INT NOT NULL,
  `objetivoOverride` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idMetaBarbeiro`),
  UNIQUE KEY `uk_meta_barbeiro` (`Meta_idMeta`,`Barbeiro_idBarbeiro`),
  CONSTRAINT `fk_MetaBarbeiro_Meta` FOREIGN KEY (`Meta_idMeta`) REFERENCES `mydb`.`Meta` (`idMeta`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_MetaBarbeiro_Barbeiro` FOREIGN KEY (`Barbeiro_idBarbeiro`) REFERENCES `mydb`.`Barbeiro` (`idBarbeiro`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Lançamentos de comissão (snapshot ao fechar período)
DROP TABLE IF EXISTS `mydb`.`ComissaoLancamento`;
CREATE TABLE `mydb`.`ComissaoLancamento` (
  `idLancamento` INT NOT NULL AUTO_INCREMENT,
  `Meta_idMeta` INT NOT NULL,
  `Barbeiro_idBarbeiro` INT NOT NULL,
  `periodoInicio` DATE NOT NULL,
  `periodoFim` DATE NOT NULL,
  `baseRealizado` DECIMAL(10,2) NOT NULL,
  `objetivoUsado` DECIMAL(10,2) NOT NULL,
  `atingiu` TINYINT(1) NOT NULL,
  `percentualAplicado` DECIMAL(5,2) NOT NULL,
  `receitaRealizada` DECIMAL(10,2) NOT NULL,
  `valorComissao` DECIMAL(10,2) NOT NULL,
  `status` ENUM('Pendente','Pago') NOT NULL DEFAULT 'Pendente',
  `criadoEm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idLancamento`),
  KEY `idx_lanc_meta_barb` (`Meta_idMeta`,`Barbeiro_idBarbeiro`),
  CONSTRAINT `fk_Lanc_Meta` FOREIGN KEY (`Meta_idMeta`) REFERENCES `mydb`.`Meta` (`idMeta`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_Lanc_Barbeiro` FOREIGN KEY (`Barbeiro_idBarbeiro`) REFERENCES `mydb`.`Barbeiro` (`idBarbeiro`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- (Opcional) Audit Log simples
DROP TABLE IF EXISTS `mydb`.`AuditLog`;
CREATE TABLE `mydb`.`AuditLog` (
  `idLog` INT NOT NULL AUTO_INCREMENT,
  `quando` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atorId` INT NULL,
  `papel` ENUM('admin','barbeiro','cliente') NULL,
  `evento` VARCHAR(64) NOT NULL,
  `alvoTipo` VARCHAR(32) NULL,
  `alvoId` INT NULL,
  `ip` VARCHAR(45) NULL,
  `detalhes` VARCHAR(255) NULL,
  PRIMARY KEY (`idLog`)
) ENGINE=InnoDB;

-- Bloqueios de horários de barbeiros (indisponibilidade)
DROP TABLE IF EXISTS `mydb`.`BloqueioHorario`;
CREATE TABLE `mydb`.`BloqueioHorario` (
  `idBloqueio` INT NOT NULL AUTO_INCREMENT,
  `Barbeiro_idBarbeiro` INT NOT NULL,
  `data` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFim` TIME NOT NULL,
  `motivo` VARCHAR(255) NULL,
  `criadoEm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idBloqueio`),
  KEY `idx_bloqueio_barbeiro_data` (`Barbeiro_idBarbeiro`,`data`,`horaInicio`,`horaFim`),
  CONSTRAINT `fk_Bloqueio_Barbeiro` FOREIGN KEY (`Barbeiro_idBarbeiro`) REFERENCES `mydb`.`Barbeiro` (`idBarbeiro`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Folga semanal recorrente (6x1) por período
DROP TABLE IF EXISTS `mydb`.`FolgaSemanal`;
CREATE TABLE `mydb`.`FolgaSemanal` (
  `idFolga` INT NOT NULL AUTO_INCREMENT,
  `Barbeiro_idBarbeiro` INT NOT NULL,
  `weekday` TINYINT NOT NULL, -- 1=Domingo ... 7=Sábado (compatível com DAYOFWEEK)
  `inicio` DATE NOT NULL,
  `fim` DATE NULL,
  `criadoEm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idFolga`),
  KEY `idx_folga_barbeiro_periodo` (`Barbeiro_idBarbeiro`,`inicio`,`fim`,`weekday`),
  CONSTRAINT `fk_Folga_Barbeiro` FOREIGN KEY (`Barbeiro_idBarbeiro`) REFERENCES `mydb`.`Barbeiro` (`idBarbeiro`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Férias/ausência prolongada do barbeiro
DROP TABLE IF EXISTS `mydb`.`FeriasBarbeiro`;
CREATE TABLE `mydb`.`FeriasBarbeiro` (
  `idFerias` INT NOT NULL AUTO_INCREMENT,
  `Barbeiro_idBarbeiro` INT NOT NULL,
  `inicio` DATE NOT NULL,
  `fim` DATE NOT NULL,
  `motivo` VARCHAR(255) NULL,
  `criadoEm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idFerias`),
  KEY `idx_ferias_barbeiro_periodo` (`Barbeiro_idBarbeiro`,`inicio`,`fim`),
  CONSTRAINT `fk_Ferias_Barbeiro` FOREIGN KEY (`Barbeiro_idBarbeiro`) REFERENCES `mydb`.`Barbeiro` (`idBarbeiro`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
